### ISSUE TITLE
Need to create regex or logic to automatically get meeting ID from meeting links

### ISSUE THREAD

**Issue by iconjone** [iconjone/ZoomUtils#1]

**Comment by jphui** [comment]
**Current validation regex:**

zoom\.us\/[a-z]{1,2}\/[^\/]+$

- matches: zoom.us/[2 letters]/[anything, but aborts when '/' detected]
- does not work on look-alike link at bottom... should figure out which "letters" are valid **call** letters

**Current extraction regex:**

[0-9]{9,}

- will match 9+ digit sets within the link
- potential edge case: if a 9+ digit set appears _before_ the actual ID, then (since the first match is returned) an incorrect ID will be identified

**Valid Links:**

https://ucla.zoom.us/j/652942891

https://us02web.zoom.us/j/82596617550?pwd=ZVJFcEx1b2JTZGpQTy9XbEtZR3FYQT09

https://ucla.zoom.us/my/jphui

https://ucla.zoom.us/w/860258885?tk=4lTWt8sosJtlcoCFm9dwxUzhjw7dZhv3h6cpSLPYFhU.DQEAAAAAM0aCRRZvQjdEWkw2aVJVNm9yNlVTZTlPUmJnAA&pwd=ZlRDbFM0V0FveFZZNit0QkZoU3RaUT09

**Invalid look-alike links:**

https://ucla.zoom.us/u/agvnMLBKb

**Comment by iconjone** [comment]
@jphui  Commit #d145a2d41660ee2e5f7d887a3dc7a92bfce13edc
